// types of correction requested
export const CORRECTION_ADDMODS = 'CORRECTION_ADDMODS'
export const CORRECTION_ADDSYN = 'CORRECTION_ADDSYN'
export const CORRECTION_COMBINE = 'CORRECTION_COMBINE'
export const CORRECTION_DELETE = 'CORRECTION_DELETE'
export const CORRECTION_DELMODS = 'CORRECTION_DELMODS'
export const CORRECTION_EDITMODS = 'CORRECTION_EDITMODS'
export const CORRECTION_MOVETOCAT = 'CORRECTION_MOVETOCAT'
export const CORRECTION_NEWNAME = 'CORRECTION_NEWNAME'
export const CORRECTION_NONE = 'CORRECTION_NONE'
export const CORRECTION_OTHER = 'CORRECTION_OTHER'
export const CORRECTION_TYPO = 'CORRECTION_TYPO'

// and their associated texts
export const CORRECTION_ADDMODS_TXT = 'Add modifiers'
export const CORRECTION_ADDSYN_TXT = 'Additional synonyms'
export const CORRECTION_COMBINE_TXT = 'Combine with other diagnosis'
export const CORRECTION_DELETE_TXT = 'Remove diagnosis completely'
export const CORRECTION_DELMODS_TXT = 'Remove modifiers'
export const CORRECTION_EDITMODS_TXT = 'Edit modifiers'
export const CORRECTION_MOVETOCAT_TXT = 'Assign to a different category'
export const CORRECTION_NEWNAME_TXT = 'Suggest different name'
export const CORRECTION_NONE_TXT = 'Correction needed...'
export const CORRECTION_OTHER_TXT = 'Other (please specify!)'
export const CORRECTION_TYPO_TXT = 'Wrong spelling / typo'
